# Generated by Django 5.1.5 on 2025-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_customuser_is_online_customuser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_connections',
            field=models.IntegerField(default=0),
        ),
    ]
